#!/usr/bin/env bash
# Creates SURVEY_TOKEN_SECRET in Firebase and mirrors it into the gitignored
# iOS Release xcconfig. Does not print the secret value.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PROJECT="${FIREBASE_PROJECT:-donanimoperasyonservis}"
SECRET_NAME="SURVEY_TOKEN_SECRET"
XCCONFIG="${ROOT}/Config/SurveyProductionSecrets.xcconfig"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

openssl rand -base64 32 | tr -d '\n' >"$TMP"
firebase functions:secrets:set "$SECRET_NAME" \
  --project "$PROJECT" \
  --data-file "$TMP" \
  --force
printf '// Generated by functions/scripts/bootstrap-survey-production.sh — do not commit\n%s = %s\n' \
  "$SECRET_NAME" "$(cat "$TMP")" >"$XCCONFIG"
echo "Firebase secret configured: $SECRET_NAME"
echo "iOS Release xcconfig written: Config/SurveyProductionSecrets.xcconfig"
